'KSGE ENVIRONMENT CHECK 
'LAUNCH BINARIES IN THE RIGHT WAY PLUS ASKS FOR HOW MANY WINNING ROW WANNA PLAY
'v1.0 20190922

dim rows as integer
'dim rowss as string
rows = 0

' let's see if we are on linux or windows
#IFDEF __FB_WIN32__
   CONST OS = "Windows 10"
#ELSE
   CONST OS = "Ubuntu Linux"
#ENDIF
'print "KSBJ FOR: " ; OS
'sleep 1000

screen 17
color 15,1
cls

print "WELCOME TO KISS STRIP BLACKJACK FOR " ; OS
print
#IFDEF __FB_WIN32__
	print
#ELSE
	print "IF YOU ARE USING UBUNTU LINUX, "
	print "THIS GAME REQUIRE VLC , XTERM AND WGET INSTALLED INTO THE SYSTEM"
	print "PLEASE INSTALL WITH: sudo apt install xterm vlc wget"
	print
#ENDIF 
print
print "PRESS ENTER TO START PLAYING WITH DEFAULT NUMBER OF WINNING ROWS (RECOMENDED)"
print "IF YOU WANT YOU CAN ALSO INPUT THE DESIRED NUMBER OF WINNING ROWS,"
print "FOR EXAMPLE IF YOU INPUT 2, THE OPPONENT WILL REMOVE A"
print "PIECE OF CLOTH WHEN SHE WILL LOOSE 2 HANDS IN A ROW"
'print "PS: FOR MAXIMUM GAME ENJOY JUST PRESS ENTER"
'print "JUST HIT ENTER"
print
input "PRESS ENTER TO START OR INPUT THE NUMBER OF WINNING ROWS: -> " ; rows

if rows > 9 then
	rows = 9
end if

if rows < 1 then 
	rows = 0
end if

cls
print "KISS STRIP BLACKJACK"
print "BASED ON KISS STRIP GAME ENGINE (KSGE)"
print
print "THIS IS FREE AND OPENSOURCE SOFTWARE"
print "YOU CAN ALSO REALIZE YOUR OWN STRIP GAME IF YOU WANT"
print
print "PLEASE SUPPORT THIS PROJECT SENDING BTC TO PLAY THE FULL GAME"
'print
'print "THIS WINDOWS AND ALSO THE OTHER LOG WINDOW CAN BE MINIMIZED"
print

#IFDEF __FB_WIN32__
	shell "start ksge.exe " + str(rows)
#ELSE
	shell "xterm -fa 'Monospace' -fs 14 -e ./ksge " + str(rows)
#ENDIF
end
